// Monster trophies (Guidebook pp. 141–188, the 'Trophies' box of each monster) and sale values (p. 79).
export const TROPHIES = {
 "Alligator Snapping Turtle": "Snapping Turtle Shell. When crafted into armor, the wearer gains +3G for Defense. If the shell is in Pristine Condition, it can replace a wagon or cabin when constructing a Mule- or Dromedary-class mech.",
 "Alpine Bigfoot": "Bigfoot Skull. This enormous skull is a prized symbol of victory over the wild. When displayed as a Mech Utility Upgrade, it acts as a source of fear. The first time an enemy is within Short Range and line of sight, they take Afraid [3B].",
 "American Bullfrog": "Bullfrog Tongue. A coarse, sticky tongue that can stretch to great lengths (up to Long Range) and snatch weapons out of enemy hands. Spend 4 Grit to pull the tongue, roll 1B, and watch it fly. On a Hit or an Ace, the weapon is taken successfully.",
 "American Mastodon": "Mastodon Tusks. If displayed as a Mech Utility Upgrade, it grants the entire posse +1G to Nerve rolls made to intimidate while riding in the mech.",
 "Badlands Sasquatch": "Scrap Collection. The Sasquatch has a vast collection of shiny gizmos and gadgets. Roll 2B6G to discover how much Scrap can be salvaged from its hoard (reroll Spurs).",
 "Bark Watcher": "Spore Pocket. When popped, the small pod explodes into a plume of spores like a smoke screen with a Short Range radius. It will also inflict Dazed [2B] to any target within that range.",
 "Black Widow and Spawn": "Venom Sack. Located within the Black Widow's abdomen, this venom sack can be removed and used to make 3G anti-venom serums. This serum removes the Lasting Effect from being Poisoned as well as the Black Widow's marked wound.",
 "Bloodsucker": "Sucker Pouch. The portion of the Bloodsucker's body used to suck up and store blood can now be used for other liquids as a storage container. Squeeze the stomach and slowly lessen your grip to suck up a liquid. Squeeze again to expel said liquid. Holds up to three liters.",
 "Bone-Carver Ant": "Carving Mandible. The ant's mandibles are strong and serrated. They can be used to clasp two things together or cut small objects like scissors.",
 "Bull Jackalope": "Lucky Rabbit's Foot. If attached to a mech as a Utility Upgrade, that mech may evade one attack once per day. To use this trophy, announce it before an attack is rolled against the mech.",
 "Burrowing Mudbugs": "Blue Exoskeleton. The Mudbug's exoskeleton can be made into a twohanded shield granting Heavy Cover to the wielder.",
 "Canadian Beaver Bear": "Beaver Bear Tail. The tough leather hide made from the tail is thick and flexible. When crafted into a wearable item, it grants the wearer immunity to the Knockback property.",
 "Carnivorous Pine": "Sticky Sap. A versatile tree sap that can be used to cement items together, create a watertight seal, or heal wounds. Roll 4B and harvest a portion of sap equal to the number of Hits rolled. Roll 1B if used as a healing item.",
 "Chupacabra": "Barbed Spines. If fashioned into an arrowhead or spear tip, it will be difficult to remove once lodged inside a target. The target takes +1B damage to remove a barb.",
 "Desert Scorpion": "Venom Chamber. Contained in this bulbous section of the scorpion's tail is a deadly neurotoxin. The player harvesting the chamber will roll with Finesse, salvaging venom to craft a number of Poison Arrows equal to the amount of Hits. These arrows each inflict Poisoned [2].",
 "Dire Wolf Pack": "Dire Wolf Pelts. If each member of the posse is wearing a Dire Wolf Pelt when the Afraid Status is inflicted upon them, they can roll with an additional +1B to relieve the Status (no additional Grit required).",
 "Dusting Moth": "Moth Dust. Enough dust can be collected from the Dusting Moth's wings to fill two small pouches. For each pouch filled, roll 1B to determine what Status (2B severity) would be inflicted if thrown at a target (2 Grit): Blank = Poisoned, Spur = Trapped, Hit = Dazed, Ace = Unconscious.",
 "Feral Hog Cyclops": "Hogwild Jerky. The hog's pork belly meat is the best you've ever tasted. If smoked and eaten, gain +2 temporary Max Health for one hour. Roll 6B6G to determine how many servings of jerky can effectively be preserved before the meat goes bad (reroll any Spurs). Limited to +2 temporary Max Health per hour, cannot be stacked.",
 "Firefox": "Firefox Pelt. A flame-resistant pelt that if made into clothes, grants the wearer +1B to rolls attempting to relieve the Burned Status.",
 "Giant Centipede": "Carapace Section. If fashioned into basic armor, it grants the wearer +1B to their Defense, plus it's lightweight enough that your movement speed remains Normal.",
 "Golden Bear": "Golden Pelt. If crafted into a wearable item, this Golden Pelt demands respect for its wearer. Increase all Reputations by one level.",
 "Grand Canyon Tarantula": "Tarantula Fangs. The internal mechanism of these fangs can be repurposed as a Venom Injector Melee Weapon Utility Upgrade. The fangs are durable, but the venom must be harvested separately.",
 "Great Golden Elk": "Golden Elk Antlers. If the antlers are carved into gun, bow, or melee weapon grips or furniture, spend an extra 1 Grit on the attack to also inflict Dazed [2]. Twice per day.",
 "Great Horned Owl": "Owl Feathers. If the owl's feathers are fashioned into a cloak, the wearer will receive +1G to Finesse rolls made to sneak at night.",
 "Horned Lizard": "Blood Pouch. This vessel has a small opening, capable of ejecting any liquid (like toxic poisons or flammable alcohol). Spend 3 Grit and roll 2B to squirt a target within Short Range, inflicting a Status relevant to the chosen liquid.",
 "Hundred-Year Hydra": "Elemental Vessel. If made into a quiver, this Vessel grants each arrow stored in it one Status [3] effect according to which of the five heads it comes from: Burned, Dazed, Trapped, Afraid, or Poisoned.",
 "Invasive Woodpecker": "Drill Beak. When used as a weapon or Melee Attachment Upgrade, spend 1 Grit to do 1G damage with Piercing [1] at Arm's Reach.",
 "King Cottonmouth": "White Death Lure. When put on display as a Mech Utility Upgrade, the white jaws of the Cottonmouth create a flash of visual impairment and intimidation. Twice per day, all creatures in line of sight and within Short Range of the Lure gain Dazed [1] and Afraid [2].",
 "Lake Guardian Moose": "Moose Antlers. When displayed as a Mech Utility Upgrade, all Small and Tiny creatures within Short Range become passive and calm. They will not attack unless provoked. Attacking or using Forstalls in this range will nullify this aura.",
 "Latcher": "Latcher Head. The head alone is of little value but it can be crushed and ground into a powder for antidotal purposes. When used as such, add 1B to your next Nerve roll intended to relieve the Poisoned Status.",
 "Lightning Bug": "Bioluminescent Abdomen. This monster part can be either used to recharge a Forstall battery up to 2 Charges, or can be shaken to illuminate a Short Range area around it for 10 minutes at a time like a lantern (limited to 10 uses before the chemicals inside no longer react to the agitation).",
 "Livewire Mudcat": "Taser Whiskers. The Mudcat's electrified whiskers can be lashed together as a whip. Be sure to wrap a non-conductive material around it for a handle. Spend 3 Grit to deal 2B damage + Electrocuted [1] at Arm's Reach.",
 "Lumberjack Mouse": "Buck Teeth. Two teeth shaped perfectly for chipping away bark. When using these teeth as a wood carving tool, swap out one black die for gold on any Finesse roll related to carpentry or woodcarving.",
 "Lurking Moss": "Moss Camouflage. If fashioned into a ghillie suit, the wearer may gain +2B to Finesse rolls made to hide or be stealthy while in a forested, mountainous, or marshy environment.",
 "Mississippi Lobster": "Lobster Shell. When crafted into armor, the lobster shell grants the wearer +2G Defense. The armor is light enough that it doesn't increase the wearer's Grit cost when taking the Move Action.",
 "North American Anaconda": "Anaconda Skin. When crafted into a wearable item, the scales of the Anaconda create armor that grants the wearer +1G Defense and +1G to Finesse or Nerve rolls made to relieve the Trapped Status.",
 "Opossum": "Prehensile Tail. The Opossum's tail is ideal for latching onto branches or stripping away weapons. If fashioned into a whip, it will deal 3B damage at Short Range, costing 4 Grit. And if 3 or more Hits are rolled, it also disarms any target holding a weapon.",
 "Ozark Howler": "Horns of the Howler. These curved horns can be turned into weapon furniture or a totemlike badge of honor. The wielder gains +1B to Charm rolls made to prove their skills and experience related to monsters.",
 "Plains Shepherd Bison": "Bull War Horn. Spend 4 Grit to blow the horn. Any allies within Short Range may remove 1 Severity level from the Afraid Status.",
 "Pondweed Peril": "Peril Pearls. The Peril swallows small stones to help with digestion. The stones become round, polished, and pearl-like \tover time. The pearls are almost always in Pristine condition worth about $25 each. Roll 3G to determine how many are harvested.",
 "Prairie Wolf": "Prairie Wolf Skull. A symbol of fierce dedication to your pack. If fashioned into a mask and worn by 2 or more players in combat, any enemy within Long Range starts that encounter with Afraid [1G].",
 "Queen Condor": "Condor Feathers. When crafted onto a wearable item, these enormous feathers reduce any damage caused from falling by 2G.",
 "Quill Archer": "Barbed Quills. The Archer's quills can be used for arrows but not all are in a condition for reuse. Roll 6B6G to determine how many quills you collect. Each arrow works the same as the monster's Barbed Quills feature.",
 "Red-Striped Skunk": "Sulfur Gland. When popped, the sulfur gland explodes in a Short Range radius, inflicting the Dazed [2B] and Poisoned [2B] Statuses.",
 "Road Runner": "Spotted Feathers. If equipped to one's person or a wielded weapon, these majestic feathers grant them the ability to move up to Long Range once during a combat encounter.",
 "Sabertooth Mountain Lion": "Saber Tooth. This elongated upper-canine can be crafted into the Cavalry Sabertooth, a melee weapon with a Grit cost of 3 and an attack of 3G + Piercing [1] at targets within Arm's Reach.",
 "Shasta Skullface": "Sickening Hide. When worn or carried, this hide inflicts the wearer with the Lasting Effect of Poisoned until taken off; however, it grants them immunity to becoming Poisoned at any Status Severity.",
 "Silver-Ringed Octopus": "Octo-bane. Arrows can be laced with the Octopus' tranquilizing poison. If so, it will inflict the target with Poisoned [1] and Unconscious [1].",
 "Slide Rock Bolter": "Bolter Slime. The Bolter's slime is extremely toxic. If ammo, arrows, and weapons are dipped in the slime, they will inflict a one-time Poisoned Status with a Severity of 3.",
 "Southern Death Worm": "Capacitor Glands. These volatile organs store an electrical charge. When attached to a weapon as a Utility Upgrade, inflict Electrocuted [3] in addition to normal damage. If used twice in the same combat scenario, the wielder also takes Electrocuted [3].",
 "Sun Warden": "Phoenix Feathers. These fire-retardant feathers can be worn to protect oneself from taking the Burned Status. The wearer can completely avoid being inflicted by the Burned Status twice per day when they choose.",
 "Terror Bird": "Hooked Beak. Use this hooked beak as a melee weapon to deal 2G damage (2 Grit). If three or more hits are rolled during a single attack, it also inflicts Unconscious[1].",
 "Trapdoor Spider": "Silk Webbing. Gain an additional +1G when determining the Severity of the Trapped Status using nets or ropes crafted from this webbing.",
 "Tunneling Grub": "Tunneling Grub Eyes. The Grub's eyes have a hard, glass-like membrane and an iris that allows sight in extremely low-light environments. If fashioned into spectacles, the wearer can see in the dark up to Long Range.",
 "Twin Diamondback": "Golden Rattle. If mounted to a mech as a Utility Upgrade, the golden rattle can be shaken to frighten monsters. Once per day, spend 3 Grit to shake the rattle and inflict Afraid [2B] on any monster within Long Range.",
 "Vampire Bat": "Anticoagulant Saliva. When an arrow or ammo is coated in this saliva and deals 3+ damage on a single attack, the target takes 1B damage at the start of each round until treated by a First Aid item. Roll 3B to determine how much saliva is collected, each Hit equals one use.",
 "Western Hellbender": "Hellbender Skin. If fashioned into an article of clothing, it lightly protects the wearer from being Poisoned by immediately reducing the Status Severity of the Status by 1.",
 "Winter Wolverine": "Winter Wolverine Pelt. This frosty mantle grants its wearer a Tolerance to being Burned. While wearing this pelt, gain an additional +1G to the Finesse rolls made to relieve the Burned Status.",
 "Yellowjacket Swarm": "Yellowjacket Stingers. Roll 6B to determine how many stingers are collected (reroll Spurs). These stingers can be used as an arrowhead inflicting Dazed [1] in addition to the damage dealt by the bow's dice pool."
};

// p. 79 Monster Trophy Value: [low, high] dollars by condition and monster size.
export const TROPHY_VALUE = {
  Pristine: { Small: [1, 10], Medium: [10, 30], Large: [30, 100], Huge: [100, 200], Titan: [200, 500] },
  Good: { Small: [0.8, 8], Medium: [8, 24], Large: [24, 80], Huge: [80, 160], Titan: [160, 400] },
  Fair: { Small: [0.6, 6], Medium: [6, 18], Large: [18, 60], Huge: [60, 120], Titan: [120, 300] },
  Poor: { Small: [0.4, 4], Medium: [4, 12], Large: [12, 40], Huge: [40, 80], Titan: [80, 200] },
};
export const CONDITIONS = ['Pristine', 'Good', 'Fair', 'Poor'];
// p. 79 Trophy Condition Ranges: what the fight was fought with.
export const CONDITION_GUIDE = [
  { range: 'Good – Pristine', with: 'Rifles, pistols, bows, traps, melee' },
  { range: 'Fair – Good', with: 'Shotguns, Burned Status' },
  { range: 'Poor – Fair', with: 'Explosives, mounted weapons' },
];
export const trophyValue = (condition, size) => (TROPHY_VALUE[condition] || {})[size === 'Tiny' ? 'Small' : size] || null;
// first sentence before ". " is the trophy's name ("Mastodon Tusks. If displayed…")
export const trophyName = (text) => String(text || '').split(/\.\s/)[0].slice(0, 60);
